### ISSUE TITLE
Agregar soporte para C++

### ISSUE THREAD

**Issue by ernestmc** [cdrfiuba/ogham-lib#3]
Actualmente la biblioteca no es compatible con C++. A primera vista dos cosas son necesario modificar para que esto funcione:
- Agregar listado de los archivos .cpp https://github.com/cdrfiuba/ogham-lib/blob/master/src/lib/setup.mk#L14
- Crear versiones .hpp de todos los headers públicos que exporten las funciones como extern "C" para que el linker las encuentre correctamente.

**Comment by tul1** [comment]
Hice las modificaciones indicadas y anduvo. Acabo de subirlo al repo.

**Comment by ernestmc** [comment]
Tener dos versiones del mismo header es difícil de mantener y una de ellas corre el riesgo de quedar desactualizada.
Sería mejor incluir compilación condicional de la siguiente manera:

```
// Funciones públicas
#ifdef __cplusplus
extern "C" {
#endif
void initBoard(void);
void initLeds(void);
void initButton(void (*isr)(void), uint8_t debounce);
uint8_t readButton(void);
void initADC(void);
#ifdef __cplusplus
}
#endif
```
